### PR TITLE
fix: correctly handle nerf-darted env vars

### LINKED ISSUE #64: [BUG] `npm_config_...` variables don't work for specifying a scoped registry password/auth/authToken
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm_config_...` variables don't work for specifying a scoped registry `_password`/`_auth`/`_authToken`. The keys are downcased, and the underscore after the colon gets [converted to a dash](https://github.com/npm/config/blob/1244177d8a68f68f2be46d5b9c21957da7dedfbb/lib/index.js#L370), so you end up with nerfed `-password`, `-auth`, and `-authtoken` keys, which `npm-registry-fetch` doesn't know how to handle. Although `getCredentialsByURI` does have some special handling for `-authtoken`, it's never actually used when doing registry fetches.

For example:

`npm_config_username=foo` -> `{ "username": "foo" }` 👍 
`npm_config__password=bar` -> `{ "_password": "bar" }` 👍  underscore is preserved
`npm_config_//my.registry.example/npm/:username=foo` -> `{ "//my.registry.example/npm/:username": "foo" }` 👍 
`npm_config_//my.registry.example/npm/:_password=bar` -> `{ "//my.registry.example/npm/:-password": "bar" }` 👎  (note the `-password`, it should be `_password`)
`npm_config_//my.registry.example/npm/:_authToken=secret` -> `{ "//my.registry.example/npm/:-authtoken": "secret" }` 👎  (note the `-authtoken`, it should be `_authToken`)

### Expected Behavior

`npm_config_//my.registry.example/npm/:_password=bar` -> `{ "//my.registry.example/npm/:_password": "bar" }` 👍
`npm_config_//my.registry.example/npm/:_authToken=secret` -> `{ "//my.registry.example/npm/:_authToken": "secret" }` 👍
 
Granted, using env vars named this way is perhaps questionable and non-portable, but based on my limited testing the approach generally works (apart from this bug 😅 ).

The value here is that env vars provide a reliable way to override local project config when you don't have a way to influence the command line args. If there were another mechanism to override project config WITHOUT using command-line args, that would also solve my current issue.

### Steps To Reproduce

_No response_

### Environment

_No response_

### PR DESCRIPTION
**Pull request by jenseng**
Preserve nerf-darted keys verbatim, since the downcasing and dasherizing can mess up both the URIs and the sub-keys themselves.

This will allow you to successfully use env vars to control registry auth, e.g. `npm_config_//reg.example/UP_CASE/:_authToken=secret` will result in a `//reg.example/UP_CASE/:_authToken` config

See #64 for more context, but the key details to note are:
1. The current logic can mess up URIs (paths may be case-sensitive, and underscores get converted to dashes)
2. The current logic dasherizes the prefix (e.g. `_password` becomes `-password`), which `npm-registry-fetch` does not handle.
3. The current logic downcases `authToken` ... although `getCredentialsByURI` has some handling around `authtoken` (and the `-` prefix), it doesn't really matter because `npm-registry-fetch` does not, so it won't get used.
4. Regarding case-sensitivity and env variables, based on my testing this should be safe/portable because:
   * For Linux/Mac/etc. variables are case-sensitive and you can use unusual characters in names
   * For Windows, although env var *accesses* are case-insensitive, the original case of the variable name is preserved when iterating or otherwise retrieving the keys, so we can reasonably pull a case-sensitive registry prefix from the key

## References
Fixes #64

### CODE REVIEW

**Comment by jenseng** [comment]
Interestingly enough `lint` works for me locally, appreciate any pointers on where to look for that one, the lines it complains about seem unrelated

**Comment by jenseng** [comment]
Also let me know if you have any thoughts/recommendations around how much to surface this in the docs.

And of course, env vars for this kind of thing definitely aren't the most user friendly approach (e.g. depending on your shell, you may have to do something like `env NPM_CONFIG_//nerf.dart...=... npm install`, but based on issues like https://github.com/npm/cli/issues/3985 it seems like there is a need.

**Comment by wraithgar** [comment]
You will need to run `npm update` to get the same linting errors locally.  There was an update to [`@npmcli/eslint-config`](https://github.com/npm/eslint-config).  Now that we're flying without package-locks it's something we have to be in the habit of doing when doing development on these modules.

**Comment by jenseng** [comment]
I created a [separate PR](https://github.com/npm/config/pull/75) for the eslint fixes, since they're happening on `main`

**Comment by wraithgar** [comment]
This PR is on my radar and I plan on getting to it this week. Thank you.

**Comment by jenseng** [comment]
Thanks @wraithgar!

File: lib/index.js [hunk 1]
```diff
@@ -367,14 +367,24 @@ class Config {
...
   }
 
+  normalizeKeyFromEnv (key) {
+    // nerf-darted keys need slightly more nuanced handling
+    if (/^\/\/.*?:./.test(key)) {
+      // preserve case and dashes within URIs
+      let [uri, k] = key.split(':', 2)
+      k = this.normalizeKeyFromEnv(k)
+      return `${uri}:${k === '_authtoken' ? '_authToken' : k}`
+    }
```
Comment (wraithgar) [inline lib/index.js:383]:
```suggestion
let [uri, k] = key.split(':')
if (uri.startsWith('//') && k) {
  // preserve case and dashes within URIs
  k = this.normalizeKeyFromEnv(k)
  return `${uri.slice(2)}:${k === '_authtoken' ? '_authToken' : k}`
}
```

This is maybe a 7/10 on the suggestion scale.  If you really think the regex is more appropriate here please push back.  We tend to default to not adding new regex (and removing existing regex) when possible, given the amount of bugs it's led to in npm the past.

Also, are we intentionally supporting `//uri:_authtoken` (lower case _authtoken)?  If we're not mucking with the case on uris do we still need to do this?

Comment (wraithgar) [reply lib/index.js:383]: disclaimer: I freehand typed that code, it may have linting/syntax errors. You may want to test and commit it locally.  I do not care about credit.

**Comment by wraithgar** [comment]
Thanks for your patience here, I ended up doing a deep dive on `npm exec` last week that took all of my focus.  This is great!  Just one suggestion and I think we can get this out this week.

File: lib/index.js (hunk 1 above)
Comment (wraithgar) [reply lib/index.js:383]: After sleeping on this I realized that this will eat any urls with ports in them.  We probably need to take another stab at this so that doesn't happen.


```
npm_config_//my.server:4242/foo:_authToken=asdf
```

This isn't a problem we've had to solve yet because of the way we search through nerf-darted configs right now, (i.e. by url specifically).

`lastIndexOf` is likely the tool for the job.

```javascript
if (key.startsWith('//') && key.includes(':')) {
  // preserve case and dashes within URIs
  const uri = key.slice(2, key.lastIndexOf(':'))
  let k = key.slice(key.lastIndexOf(':') + 1)
  k = this.normalizeKeyFromEnv(k)
  return `${uri}:${k === '_authtoken' ? '_authToken' : k}`
}
```

Comment (jenseng) [reply lib/index.js:383]: Sounds great, I've been offline for a couple days but will push a patch in the next day or so

Comment (jenseng) [reply lib/index.js:383]: re: `//uri:_authtoken` on that line, it's moreso that I was maintaining the existing "key are case-insensitive" functionality where possible ... i.e. a nerfed key could have any case coming in (e.g. `//uri:_PASSWORD=...`), so we `normalizeKeyFromEnv` the sub-key on the next line. But then `_authtoken` then needs to be changed to `_authToken` since that's what various things downstream expect 😅

It's definitely a little weird, so if we're ok with saying that nerfed keys are case sensitive that could simplify this a bit... no need to normalize the sub-key or have special handling for `_authToken`. WDYT?

Comment (jenseng) [reply lib/index.js:383]: one other note, we don't actually want to lop of the leading `//`, since all this function does is normalize casing/dashes where appropriate, we still want a fully nerfed config key including the slashes

Comment (wraithgar) [reply lib/index.js:383]: re case sensitivity: Windows is going to be the place to make sure things work as expected.  I know you can read from process.env ignoring case, but if you are iterating its keys, does it retain what was originally used?

Comment (jenseng) [reply lib/index.js:383]: Yes, when iterating the keys in Windows you get the original value, e.g. under the `Output env` and `Output env 2` steps [here](https://github.com/jenseng/workflow-test/runs/7749300740?check_suite_focus=true) you can see the results of doing `for (let key in process.env) console.log(key)` under PowerShell and CMD.exe respectively, variable names like `mixed_CASE` and `something_//really-weird.LOL:_ok` are preserved

Comment (jenseng) [reply lib/index.js]: Ok updated, it's much simpler now 😅

Comment (wraithgar) [reply lib/index.js]: That's an understatement!

**Review by wraithgar — APPROVED** [review]
